### ISSUE TITLE
何时上mooc？物理系大三是不是已经没机会了……

### ISSUE THREAD

**Issue by Diyorazh** [heroxbd/physics-data#1]
如题

**Comment by heroxbd** [comment]
> 如题

大三去暑研吗？时间允许不？

会有录像和讲义的。

**Comment by Diyorazh** [comment]
对，我去ucsd，六月底就走。
我不是做大数据的，但是各种科研都要搞计算包。
所以学一下还是更放心，之前都是自己一通抓瞎，配环境配的也很痛苦……

**Comment by heroxbd** [comment]
> 对，我去ucsd，六月底就走。
> 我不是做大数据的，但是各种科研都要搞计算包。
> 所以学一下还是更放心，之前都是自己一通抓瞎，配环境配的也很痛苦……

嗯，理解了。你的需要与课程设计的目标一致。
